#pragma once
typedef unsigned char uint_8;
typedef unsigned short uint_16;
typedef unsigned int uint_32;
typedef unsigned long long uint_64;

#define NULL 0

#define FOREGROUND_BLACK 0x00
#define FOREGROUND_BLUE 0x01
#define FOREGROUND_GREEN 0x02
#define FOREGROUND_CYAN 0x03
#define FOREGROUND_RED 0x04
#define FOREGROUND_MAGENTA 0x05
#define FOREGROUND_BROWN 0x06
#define FOREGROUND_LIGHTGRAY 0x07
#define FOREGROUND_DARKGRAY 0x08
#define FOREGROUND_LIGHTBLUE 0x09
#define FOREGROUND_LIGHTGREEN 0x0A
#define FOREGROUND_LIGHTCYAN 0x0B
#define FOREGROUND_LIGHTRED 0x0C
#define FOREGROUND_LIGHTMAGENTA 0x0D
#define FOREGROUND_YELLOW 0x0E
#define FOREGROUND_WHITE 0x0F


#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x010
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_CYAN 0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_LIGHTGRAY 0x70

#define BACKGROUND_BRIGHTBLACK 0x80
#define BACKGROUND_BRIGHTBLUE 0x90
#define BACKGROUND_BRIGHTGREEN 0xA0
#define BACKGROUND_BRIGHTCYAN 0xB0
#define BACKGROUND_BRIGHTRED 0xC0
#define BACKGROUND_BRIGHTMAGENTA 0xD0
#define BACKGROUND_BRIGHTYELLOW 0xE0
#define BACKGROUND_BRIGHTWHITE 0xF0